### ISSUE TITLE
Add Prefix & Suffix Widget in TextField

### ISSUE THREAD

**Issue by omjogani** [opxica/modular-ui#110]
Currently TextField doesn't have any icon as prefix icon or suffix icon. It's better to have optional prefix and suffix icon. So, When User need it they can directly used for performing different actions on textfield.

## Currently
![image](https://github.com/opxica/modular-ui/assets/72139914/8c8b0de0-4428-467e-b06b-07a42b9e1e25)

### Prefix Icon
![image](https://github.com/opxica/modular-ui/assets/72139914/5966f163-88a3-486a-bef6-319686051d87)

### Suffix Icon
![image](https://github.com/opxica/modular-ui/assets/72139914/1f35942c-6415-42d0-8e30-ce953291560d)

## Development Walkthrough
- Create optional parameter for `prefixIcon` & `suffixIcon` in `lib/src/input_fields/primary_input_field.dart`.
- Pass the parameters to the actual components.
- Test the Component is it working as expected.
- onClick is working perfectly or not.
- Raise the PR of your code

**Comment by Utkarsh4517** [comment]
#113

**Comment by omjogani** [comment]
#113 Merged to `development` 🔥
