### ISSUE TITLE
Implement Alert Dialog

### ISSUE THREAD

**Issue by Yash-Khattar** [opxica/modular-ui#16]
Issue Description: Flutter Alert Dialog Implementation

Description:
The task is to create a Alert Dialog in Flutter, mimicking the design provided in the ShadCN documentation for an Alert Dialog

Link to UI - https://ui.shadcn.com/docs/components/alert-dialog

Requirements:

Ensure that the Flutter Alert Dialog closely resembles the provided Shadcn.
The component should adapt well to different screen sizes and orientations.
Allow dynamic content insertion into the component. Placeholder data can be used for testing purposes.
Testing Guidelines:

Verify that the component displays correctly on various devices and screen sizes.
Test the dynamic content integration by replacing placeholder data with real data.
Ensure that any interactive elements respond as expected.

**Comment by laksh29** [comment]
Heyy @Yash-Khattar !!
This seems interesting... Can I take it up ?

**Comment by Yash-Khattar** [comment]
Sure, assigned it to you :)

**Comment by laksh29** [comment]
Hey @Yash-Khattar 
Here are the previews of the Dialog box as per the UI in all 3 devices (Web, tab, mobile)
The 'Show Dialog' button is customizable, and the Dialog box, contents, and action buttons are customizable. 

### Web Preview
<img width="1710" alt="Screenshot 2024-01-07 at 1 34 54 PM" src="https://github.com/opxica/modular-ui/assets/81346526/b7f78c48-09a3-42eb-95e6-fe154fdd7000">

### Mobile Preview
<img width="405" alt="Screenshot 2024-01-07 at 1 35 30 PM" src="https://github.com/opxica/modular-ui/assets/81346526/e03c7ecf-5535-4103-b1b7-d8934c1e2974">

### Tab Preview
<img width="631" alt="Screenshot 2024-01-07 at 1 36 17 PM" src="https://github.com/opxica/modular-ui/assets/81346526/5b1945ad-ae82-4828-abc5-59f432aa5fa1">

**Comment by laksh29** [comment]
Let me know if this works, or if any changes are required. 
I'll create a PR accordingly.

**Comment by Yash-Khattar** [comment]
It's perfect!
Make the PR, I'll check and let you know if there are any changes in the code

**Comment by laksh29** [comment]
[Here is the PR](https://github.com/opxica/modular-ui/pull/28)
