### ISSUE TITLE
Implement Blog Card

### ISSUE THREAD

**Issue by Yash-Khattar** [opxica/modular-ui#17]
Issue Description: Flutter Blog Card Implementation

Description:
The task is to create a Blog card in Flutter, mimicking the design provided in the Material Tailwind UI documentation for a profile card.

Link to UI - https://www.material-tailwind.com/docs/react/card#blog-card

Requirements:

Ensure that the Flutter blog card closely resembles the provided Material Tailwind UI profile card.
The component should adapt well to different screen sizes and orientations.
Allow dynamic content insertion into the component. Placeholder data can be used for testing purposes.
Testing Guidelines:

Verify that the profile card displays correctly on various devices and screen sizes.
Test the dynamic content integration by replacing placeholder data with real data.
Ensure that any interactive elements respond as expected.

**Comment by sam-shot** [comment]
Can I work on this?

**Comment by Yash-Khattar** [comment]
Sure assigned it to you,
let us know if you face any issues!

**Comment by dev-o-los** [comment]
I would also like to work on this!!
