### ISSUE TITLE
Create a flutter web app 

### ISSUE THREAD

**Issue by Utkarsh4517** [opxica/modular-ui#20]
Create a flutter web app which acts as a console to view and use every widget of ModularUI

Needs to be discussed.

**Comment by oxelf** [comment]
I would recommend widgetbook, it’s really nice for ordering and building out ui elements. You can preview different themes, adjust dynamic the widgets parameters and a lot more. I could set it up if you want. https://www.widgetbook.io/ 
<img width="540" alt="IMG_4322" src="https://github.com/opxica/modular-ui/assets/110409182/e4970f76-35e0-448c-a6bf-76ae40d9985a">

**Comment by Utkarsh4517** [comment]
Perfect 💯. I am assigning this to you

**Comment by Utkarsh4517** [comment]
Hey we are creating a new repo for wrapping and hosting all of those widgets under WidgetBook.
Thankyou @oxelf
