### ISSUE TITLE
[Suggestion] - Replace getScreenWidth(context) with {num}.sw(context) and getScreenHeight(context) with {num}.sh(context)

### ISSUE THREAD

**Issue by dev-o-los** [opxica/modular-ui#33]
This is much easier to understand and removes the need of {*} operator.

the abbreviation `sh` and `sw` stands for `screenHeight` and `screenWidth` respectively.

Code Implementation is down below

```
extension NumExt on num {
  double sh(BuildContext context) =>
      this * MediaQuery.of(context).size.height / 100;

  double sw(BuildContext context) =>
      this * MediaQuery.of(context).size.width / 100;
}

```

**Comment by dev-o-los** [comment]
For example

```
20.sh(context) => //20 percent of screen height

20.sw(context) => //20 percent of screen width

```

**Comment by Utkarsh4517** [comment]
I guess we can do this. But we will need to change it everywhere. If you have enough time then you can go for it. @dev-o-los

**Comment by dev-o-los** [comment]
I'll try my best @Utkarsh4517
