### ISSUE TITLE
Implement Avatar

### ISSUE THREAD

**Issue by oxelf** [opxica/modular-ui#36]
Issue Description: Implement Avatar Component

Description:
The task is to create the avatar component in Flutter, mimicking the design provided in the Shadcn documentation for a avatar.

Link to UI - https://ui.shadcn.com/docs/components/avatar

Requirements:

- Should look and feel close to the Avatar component from Shadcn.
- Needs to support fallback text, predefined size, bgColor. 

Can somebody assign me for this?

**Comment by Strange-Philip** [comment]
hello, can i take this up?

**Comment by oxelf** [comment]
I guess so, but I can’t assign you, somebody else needs to do that

**Comment by Strange-Philip** [comment]
@Yash-Khattar @Aadhithya-D @Utkarsh4517

**Comment by Strange-Philip** [comment]
thanks...working on it...
