### ISSUE TITLE
Implement Switch

### ISSUE THREAD

**Issue by sabowsla** [opxica/modular-ui#39]
Issue Description: Implement SwitchComponent

Description:
The task is to create the switch component in Flutter, mimicking the design provided in the Shadcn documentation for a switch.

Link to UI - https://ui.shadcn.com/docs/components/switch

Requirements:

Should look and feel close to the Switchcomponent from Shadcn.
Needs to support predefined size, bgColor.
Can somebody assign me for this?

**Comment by Utkarsh4517** [comment]
Assigned it to you

**Comment by sabowsla** [comment]
#40
