### ISSUE TITLE
Implement Radio Button

### ISSUE THREAD

**Issue by sabowsla** [opxica/modular-ui#42]
Issue Description: Implement Radio Button Component

Description:
The task is to create the Radio component in Flutter, mimicking the design provided in the Shadcn documentation for a Radio .

Link to UI - https://ui.shadcn.com/docs/components/radio-group

Requirements:

Should look and feel close to the Radio Button component from Shadcn.
Needs to support predefined size, bgColor.
Can somebody assign me for this?

**Comment by Utkarsh4517** [comment]
Assigned it to you

**Comment by sabowsla** [comment]
merge at development #44
