### ISSUE TITLE
Implement Carausel 

### ISSUE THREAD

**Issue by Utkarsh4517** [opxica/modular-ui#84]
Here's the link 
https://www.material-tailwind.com/docs/react/carousel

**Comment by Strange-Philip** [comment]
can i help with this @Utkarsh4517 ?

**Comment by Utkarsh4517** [comment]
Yeah sure @Strange-Philip

**Comment by Strange-Philip** [comment]
thanks ...on it

**Comment by Strange-Philip** [comment]
I created the pull request for this issue
Here is a gif for demo
![Uploading carousell.gif…]()

**Comment by Strange-Philip** [comment]
![carousell](https://github.com/opxica/modular-ui/assets/68474949/a1cfac73-fb63-45b8-9020-a65f88516aa2)
