### ISSUE TITLE
Implement Slider

### ISSUE THREAD

**Issue by Utkarsh4517** [opxica/modular-ui#91]
https://www.material-tailwind.com/docs/react/slider

**Comment by Strange-Philip** [comment]
can i work on this @Utkarsh4517 ?

**Comment by Strange-Philip** [comment]
Got the ui to optimum visuals but im having issues with functionality:{making the thumb move with the value}- would appreciate any help i can get @Utkarsh4517

**Comment by Strange-Philip** [comment]
![simulator_screenshot_D2E06F9D-94E9-4C79-A9DD-E5651ABFDC9E](https://github.com/opxica/modular-ui/assets/68474949/6f1b8bb6-c40f-44fb-b191-1825c067faaa)
